### PR TITLE
OCF update (mostly bugfix)

### LINKED ISSUE #728: Kernel BUGs while running I/O (eviction paths)
## Description
Kernel BUG while running I/O to/from the CAS device.

## Expected Behavior
I/O completed successfully

## Actual Behavior
Kernel BUG - logs attached below

## Steps to Reproduce
1. Start cache and add core
2. Disable udev
3. Create xfs filesystem and mount CAS device
4. Run I/O to the mountpoint

## Logs

> [20266.611221] cache1: Super block runti[20279.757894] bash (156629): drop_caches: 3
> [20287.832873] ------------[ cut here ]------------
> [20287.839804] kernel BUG at /root/open-cas-linux/modules/cas_cache/src/ocf/eviction/lru.c:151!
> [20287.850685] invalid opcode: 0000 [#1] SMP PTI
> [20287.857494] CPU: 12 PID: 156053 Comm: cas_io_1_12 Kdump: loaded Tainted: G        W  OE    --------- -  - 4.18.0-240.el8.x86_64 #1
> [20287.874676] Hardware name: Intel Corporation S2600WFQ/S2600WFQ, BIOS SE5C620.86B.02.01.0008.031920191559 03/19/2019
> [20287.887997] RIP: 0010:remove_lru_list+0x176/0x180 [cas_cache]
> [20287.896657] Code: 5e 41 5f c3 0f 0b 8b 53 0c 85 d2 74 09 44 89 63 10 e9 6a ff ff ff 0f 0b 8b 4b 0c 85 c9 75 13 c7 43 10 ff ff ff ff eb bd 0f 0b <0f> 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 1f 44 00 00 41 54 55 53 8b 2e 8b
> [20287.921673] RSP: 0018:ffffa81e6035fd28 EFLAGS: 00010246
> [20287.930065] RAX: 00000000ffffffff RBX: ffffa81e6026a0d0 RCX: 0000000000000000
> [20287.940405] RDX: 0000000000021400 RSI: ffffa81e469bd330 RDI: ffffa81e60139000
> [20287.950730] RBP: ffffa81e6173566d R08: 0000000000000000 R09: 0000000000000000
> [20287.961093] R10: ffffa81e62134000 R11: 0000000000000010 R12: 00000000ffffffff
> [20287.971440] R13: 0000000000021445 R14: ffffa81e60139000 R15: 00000000ffffffff
> [20287.981702] FS:  0000000000000000(0000) GS:ffff9b8610900000(0000) knlGS:0000000000000000
> [20287.992889] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
> [20288.001715] CR2: 000055981fffd630 CR3: 00000001cd60a001 CR4: 00000000007606e0
> [20288.011967] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
> [20288.022234] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
> [20288.032487] PKRU: 55555554
> [20288.038192] Call Trace:
> [20288.043503]  evp_lru_rm_cline+0x87/0xb0 [cas_cache]
> [20288.051229]  __set_cache_line_invalid+0xf7/0x120 [cas_cache]
> [20288.060156]  set_cache_line_invalid_no_flush+0x59/0x80 [cas_cache]
> [20288.069426]  ocf_engine_evict+0x82/0xd0 [cas_cache]
> [20288.077246]  ocf_engine_prepare_clines+0x1fa/0x4f0 [cas_cache]
> [20288.086096]  ? cas_garbage_collector_deinit+0x80/0x80 [cas_cache]
> [20288.095273]  ocf_write_wb+0x46/0xe0 [cas_cache]
> [20288.102935]  ocf_queue_run+0x23/0x40 [cas_cache]
> [20288.110720]  _cas_io_queue_thread+0x6a/0x100 [cas_cache]
> [20288.119263]  ? finish_wait+0x80/0x80
> [20288.126100]  kthread+0x112/0x130
> [20288.132614]  ? kthread_flush_work_fn+0x10/0x10
> [20288.140411]  ret_from_fork+0x35/0x40
> [20288.147366] Modules linked in: xfs dm_mod xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 nft_compat nft_counter nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c nls_utf8 isofs nf_tables nfnetlink tun loop bridge stp llc rpcsec_gss_krb5 auth_rpcgss nfsv4 dns_resolver nfs lockd grace fscache sunrpc vfat fat sha512_ssse3 sha512_generic intel_rapl_msr intel_rapl_common iTCO_wdt isst_if_common iTCO_vendor_support skx_edac nfit libnvdimm x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel intel_cstate cas_cache(OE) qat_c62x intel_uncore ipmi_ssif cas_disk(OE) intel_qat mei_me ioatdma intel_rapl_perf pcspkr joydev mei lpc_ich ipmi_si i2c_i801 dca dh_generic wmi ipmi_devintf ipmi_msghandler acpi_power_meter acpi_pad ip_tables ext4 mbcache jbd2 sd_mod sg i2c_algo_bit drm_vram_helper drm_ttm_helper ttm drm_kms_helper syscopyareind hash table entries: 2048 (order: 3, 32768 bytes)
> 

## Your Environment

* OpenCAS version (commit hash or tag): 21.03.0.0468.master
* Operating System: RHEL 8.3
* Kernel version: 4.18.0-240.el8.x86_64
* Cache device type (NAND/Optane/other): Optane

### LINKED ISSUE #729: kernel BUG at cas_cache module: /eviction/lru.c:151
## Description
After disabling cleaning and sequential cutoff and then running IO on CAS device kernel bug occurred.

## Expected Behavior
running IO successfully.

## Actual Behavior
Kernel BUGs - system breakdown

## Steps to Reproduce
test_concurrent_flushes.py
1. prepare caches (3) and cores (3)
2. start caches
3. disable cleaning and sequential cutoff
4. add core devices to caches
5. run workload on each CAS devices ( with dd)

## Logs
[serial.log](https://github.com/Open-CAS/open-cas-linux/files/6141774/serial.log)

## Your Environment
* OpenCAS version (commit hash or tag): 21.03.0.0468.master a70a862
* Operating System: RHEL 8.3
* Kernel version: 4.18.0-240.el8.x86_64
* Cache device type (NAND/Optane/other): Optane, NAND
* Core device type (HDD/SSD/other): HDD

### LINKED ISSUE #735: Kernel BUGs while running I/O
Description
Kernel BUG while running I/O to/from the CAS device.

Expected Behavior
I/O completed successfully

Actual Behavior
Kernel BUG - logs attached below

Steps to Reproduce
Start cache and add core
Disable udev
Create xfs filesystem and mount CAS device
Run I/O to the mountpoint

```
[18202.674960] cache1: Purging cache
[18226.070245] ------------[ cut here ]------------
[18226.077416] kernel BUG at /root/open-cas-linux/modules/cas_cache/src/ocf/eviction/lru.c:659!
[18226.088536] invalid opcode: 0000 [#1] SMP PTI
[18226.095575] CPU: 7 PID: 141264 Comm: cas_io_1_7 Kdump: loaded Tainted: G W OE --------- - - 4.18.0-240.el8.x86_64 #1
[18226.112833] Hardware name: Intel Corporation S2600WFQ/S2600WFQ, BIOS SE5C620.86B.02.01.0008.031920191559 03/19/2019
[18226.126304] RIP: 0010:evp_lru_req_clines+0x4db/0x530 [cas_cache]
[18226.135371] Code: 24 08 48 c7 c1 ff ff ff ff 48 0f 44 c1 83 c0 01 e9 2a fc ff ff 89 74 24 54 e9 4e fe ff ff 80 4c 18 13 02 e9 22 ff ff ff 0f 0b <0f> 0b 4c 8b 74 24 10 49 8b be 88 00 00 00 e8 f2 c7 fe ff 49 8b be
[18226.160581] RSP: 0000:ffffbdcfa0eb7c58 EFLAGS: 00010282
[18226.169225] RAX: 00000000000000ce RBX: 0000000000000300 RCX: 0000000000000020
[18226.179524] RDX: ffff94b28bb605d0 RSI: 0000000000000021 RDI: ffffbdcf869b5000
[18226.189828] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000020
[18226.200144] R10: ffff94b28bb605d0 R11: ffffbdcfa4e76000 R12: 0000000000000020
[18226.210477] R13: 0000000000000002 R14: 0000000000000001 R15: ffffbdcfa108d000
[18226.221023] FS: 0000000000000000(0000) GS:ffff94b2d07c0000(0000) knlGS:0000000000000000
[18226.232477] CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[18226.241219] CR2: 00007fff102dc9a0 CR3: 00000017f3a0a006 CR4: 00000000007606e0
[18226.251359] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[18226.261540] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[18226.271737] PKRU: 55555554
[18226.277533] Call Trace:
[18226.283081] ? generic_make_request+0xcf/0x310
[18226.290704] space_managment_evict_do+0x2ed/0x410 [cas_cache]
[18226.299709] ocf_engine_evict+0x13/0xd0 [cas_cache]
[18226.307896] ocf_engine_prepare_clines+0x1fa/0x4f0 [cas_cache]
[18226.317104] ? cas_garbage_collector_deinit+0x80/0x80 [cas_cache]
[18226.326636] ocf_read_generic+0x58/0xf0 [cas_cache]
[18226.335009] ocf_queue_run+0x23/0x40 [cas_cache]
[18226.343155] _cas_io_queue_thread+0x6a/0x100 [cas_cache]
[18226.352055] ? finish_wait+0x80/0x80
[18226.359244] kthread+0x112/0x130
[18226.366114] ? kthread_flush_work_fn+0x10/0x10
[18226.374273] ret_from_fork+0x35/0x40
[18226.381588] Modules linked in: xfs dm_mod xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 nft_compat nls_utf8 isofs nft_counter loop nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c nf_tables nfnetlink rpcsec_gss_krb5 auth_rpcgss tun bridge stp llc nfsv4 dns_resolver nfs lockd grace fscache sunrpc vfat fat sha512_ssse3 sha512_generic intel_rapl_msr intel_rapl_common isst_if_common iTCO_wdt iTCO_vendor_support skx_edac nfit libnvdimm x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass ipmi_ssif crct10dif_pclmul crc32_pclmul cas_cache(OE) ghash_clmulni_intel intel_cstate qat_c62x intel_qat intel_uncore cas_disk(OE) pcspkr intel_rapl_perf ipmi_si dh_generic mei_me ioatdma joydev i2c_i801 lpc_ich ipmi_devintf mei dca wmi ipmi_msghandler acpi_pad acpi_power_meter ip_tables ext4 mbcache jbd2 sd_mod sg i2c_algo_bit drm_vram_helper drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect sysimgblt ahci fb_sys_fops libahci i40e
[18226.381617] megaraid_sas drm crc32c_intel nvme libata nvme_core
[ 0.000000] Linux version 4.18.0-240.el8.x86_64 (mockbuild@x86-vm-09.build.eng.bos.redhat.com) (gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)) #1 SMP Wed Sep 23 05:13:10 EDT 2020
```

Your Environment
OpenCAS version (commit hash or tag): 21.03.0.0468.master
Operating System: RHEL 8.3
Kernel version: 4.18.0-240.el8.x86_64
Cache device type (NAND/Optane/other): Optane

### PR DESCRIPTION
**Pull request by arutk**
fixes #729
fixes #728
fixes #735 

Signed-off-by: Adam Rutkowski <adam.j.rutkowski@intel.com>

### CODE REVIEW

**Comment by arutk** [comment]
Fixes #729

**Comment by arutk** [comment]
fixes #729

**Comment by arutk** [comment]
fixes #728

**Comment by arutk** [comment]
fixes #735

**Review by Ostrokrzew — APPROVED** [review]

**Review by mmichal10 — APPROVED** [review]

**Pull request merged**
