### PR TITLE
Enable setting acp params.

### PR DESCRIPTION
**Pull request by mmichal10**
Fixes #115

Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>

### CODE REVIEW

**Comment by mmichal10** [comment]
Fixes #115

**Comment by mmichal10** [comment]
retest this please

**Comment by Deixx** [comment]
retest this please

**Comment by micrakow** [comment]
retest this please

**Comment by KamilLepek** [comment]
@CAS-Linux-Jenkins retest this please

**Pull request merged**
