### PR TITLE
utils: lengthen open-cas service timeout

### PR DESCRIPTION
**Pull request by liuhongtong**
Signed-off-by: liuhongtong <hongtongliu@126.com>

### CODE REVIEW

**Comment by robertbaldyga** [comment]
ok to test

**Comment by imjfckm** [comment]
Thanks for the PR, @liuhongtong !
Why exactly do you want this timeout to be longer? Is there any specific issue you're encountering?
Also, timeout in systemd service file is just a safeguard in case something goes really wrong - the real timeout you should be looking at is a line above in `ExecStart=/sbin/casctl settle --timeout 150 --interval 5`. This is the time after which te service will fail if devices won't start.

**Comment by liuhongtong** [comment]
@imjfckm Thanks for your attention.
There are at least four NVMe SSDs in my system, maybe more in the future. Init cache devices needs a long time, that leads to  open-cas service starting failure and os entering emergency mode.

**Comment by imjfckm** [comment]
Sounds reasonable to me! I do have some doubts still. Does the patch fix it for you? Without changing the timeout in `ExecStart` ?

**Comment by liuhongtong** [comment]
@imjfckm Thanks. I will retest this issue.

**Comment by imjfckm** [comment]
@liuhongtong any update on this?

**Pull request merged**
