### PR TITLE
atomic: move setting up context before sub io allocation

### PR DESCRIPTION
**Pull request by micrakow**
Signed-off-by: Michal Rakowski <michal.rakowski@intel.com>

### CODE REVIEW

**Comment by micrakow** [comment]
@CAS-Linux-Jenkins retest this please

**Comment by micrakow** [comment]
retest this please

**Comment by robertbaldyga** [comment]
retest this please

**Comment by robertbaldyga** [comment]
retest this please

**Comment by robertbaldyga** [comment]
retest this please

**Pull request merged**
