### PR TITLE
Upgrade in flight for RPM

### PR DESCRIPTION
**Pull request by rafalste**
Signed-off-by: Rafal Stefanowski <rafal.stefanowski@intel.com>

### CODE REVIEW

**Comment by imjfckm** [comment]
Isn't this something we'd like to do in utils/upgrade script? Seems to me like this is redundant and yet another utility serving more or less the same purpose. Or maybe remove utils/upgrade and implement this functionality here?

I think we should have some kind of discussion where do we want to go with this. @robertbaldyga  @arutk @mmichal10 ?

**Comment by mmichal10** [comment]
@imjfckm @rafalste 

`utils/upgrade` script has few additional checks, which are missing in this script - check for empty corepool, check for missing cores. Those checks have to be added if we would like to merge @rafalste patch.

I would like you to keep in mind that our test API will also require utility for RPM. Do you think it be good idea to create one utility to be used by tests and by `utils/upgrade`? This could save us some time for maintenance in the future.

**Comment by rafalste** [comment]
I could add those checks mentioned by @mmichal10 if they are necessary.

Regarding one utility which can be used by tests and by upgrade script, I think there might be some obstacles with this approach, but maybe someone more experienced can share his opinion.

**Comment by imjfckm** [comment]
Overall I'm against creating new separate tool for RPM upgrades and think we should incorporate this functionality in already existing `utils/upgrade`. Unless it poses significant problems IMO that's the way we should go.

**Comment by Deixx** [comment]
@CAS-Linux-Jenkins retest this please

**Comment by robertbaldyga** [comment]
We no longer support upgrade in flight.

**Pull request closed without merging**
