### PR TITLE
Update OCF version

### LINKED ISSUE #86: Scheduling while atomic in ocf_async_unlock
open-cas-linux commit: 3812015

The following warning occurs after running FIO in WB mode:

[  969.561114] BUG: scheduling while atomic: swapper/7/0/0x10010000   
[  969.562015] Modules linked in: cas_cache(OE) ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set
 nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6tabl
e_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security i
ptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter xfs libcrc32c cas_disk(OE) ppdev sg pcspkr joydev parport
_pc parport i2c_piix4 ip_tables btrfs xor raid6_pq sd_mod crc_t10dif crct10dif_generic sr_mod cdrom crct10dif_common ata_generic virti
o_blk pata_acpi cirrus drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm drm ata_piix libata e1000 virtio_pci virtio_ri
ng floppy i2c_core virtio serio_raw [last unloaded: cas_cache]
[  969.562015] CPU: 7 PID: 0 Comm: swapper/7 Tainted: G   OE  ------------   3.10.0-693.el7.x86_64 #1 
[  969.562015] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.7.5-0-ge51488c-20140602_164612-nilsson.home.kraxel.or
g 04/01/2014  
[  969.562015]  ffff88017a11c000 b91d71f1fff90dd8 ffff880424fc3ac0 ffffffff816a3d91   
[  969.562015]  ffff880424fc3ad0 ffffffff8169e202 ffff880424fc3b30 ffffffff816a93f7   
[  969.562015]  ffff88017a120000 ffff88017a11ffd8 ffff88017a11ffd8 ffff88017a11ffd8   
[  969.562015] Call Trace:
[  969.562015]  <IRQ>  [<ffffffff816a3d91>] dump_stack+0x19/0x1b  
[  969.562015]  [<ffffffff8169e202>] __schedule_bug+0x64/0x72 
[  969.562015]  [<ffffffff816a93f7>] __schedule+0x807/0x8b0   
[  969.562015]  [<ffffffff810c13e6>] __cond_resched+0x26/0x30 
[  969.562015]  [<ffffffff816a976a>] _cond_resched+0x3a/0x50  
[  969.562015]  [<ffffffff816a7722>] mutex_lock+0x12/0x2f 
[  969.562015]  [<ffffffffc05b5c8c>] ocf_async_unlock+0x3c/0xa0 [cas_cache]   
[  969.562015]  [<ffffffffc05b0c8e>] ocf_mngt_cache_unlock+0x1e/0x30 [cas_cache]  
[  969.562015]  [<ffffffffc059a403>] ocf_cleaner_run_complete+0x23/0x40 [cas_cache]   
[  969.562015]  [<ffffffffc059954b>] alru_clean_complete+0x4b/0x50 [cas_cache]
[  969.562015]  [<ffffffffc05b642f>] _ocf_cleaner_complete_req+0x4f/0x60 [cas_cache]  
[  969.562015]  [<ffffffffc05b6463>] _ocf_cleaner_finish_req+0x23/0x30 [cas_cache]
[  969.562015]  [<ffffffffc05b64a9>] _ocf_cleaner_flush_cache_io_end+0x39/0x50 [cas_cache]
[  969.562015]  [<ffffffffc058c280>] cas_bd_io_end+0x40/0x50 [cas_cache]  
[  969.562015]  [<ffffffffc058c2fe>] cas_bd_io_end_callback+0x6e/0xe0 [cas_cache] 
[  969.562015]  [<ffffffff8123c914>] bio_endio+0x64/0xa0  
[  969.562015]  [<ffffffff812f91f0>] blk_update_request+0x90/0x360
[  969.562015]  [<ffffffff813023ca>] blk_mq_end_request+0x1a/0x70 
[  969.562015]  [<ffffffff812fc366>] blk_flush_complete_seq+0xd6/0x2c0
[  969.562015]  [<ffffffff812fc7e0>] flush_end_io+0x160/0x250 
[  969.562015]  [<ffffffff813023ea>] blk_mq_end_request+0x3a/0x70 
[  969.562015]  [<ffffffffc00833af>] virtblk_request_done+0x3f/0x70 [virtio_blk]  
[  969.562015]  [<ffffffff8130249d>] __blk_mq_complete_request+0x7d/0x100 
[  969.562015]  [<ffffffff81302547>] blk_mq_complete_request+0x27/0x30
[  969.562015]  [<ffffffffc008307c>] virtblk_done+0x7c/0x110 [virtio_blk] 
[  969.562015]  [<ffffffffc001b578>] vring_interrupt+0x38/0x90 [virtio_ring]  
[  969.562015]  [<ffffffff81130a2e>] __handle_irq_event_percpu+0x3e/0x1c0 
[  969.562015]  [<ffffffff81130be2>] handle_irq_event_percpu+0x32/0x80
[  969.562015]  [<ffffffff81130c6c>] handle_irq_event+0x3c/0x60   
[  969.562015]  [<ffffffff811338f7>] handle_edge_irq+0x77/0x130   
[  969.562015]  [<ffffffff8102d2c8>] handle_irq+0xb8/0x150
[  969.562015]  [<ffffffff810f3ddc>] ? tick_check_idle+0x8c/0xd0  
[  969.562015]  [<ffffffff816b053a>] ? atomic_notifier_call_chain+0x1a/0x20   
[  969.562015]  [<ffffffff816b75ed>] do_IRQ+0x4d/0xe0 
[  969.562015]  [<ffffffff816ac1ed>] common_interrupt+0x6d/0x6d   
[  969.562015]  <EOI>  [<ffffffff816ab4a6>] ? native_safe_halt+0x6/0x10   
[  969.562015]  [<ffffffff816ab33e>] default_idle+0x1e/0xc0   
[  969.562015]  [<ffffffff81035006>] arch_cpu_idle+0x26/0x30  
[  969.562015]  [<ffffffff810e7bca>] cpu_startup_entry+0x14a/0x1c0
[  969.562015]  [<ffffffff81051af6>] start_secondary+0x1b6/0x230

### LINKED ISSUE #87: Kernel bug when starting cache with insufficient amount of RAM
open-cas-linux commit: 3812015

The following is printed to dmesg when attempting to start cache with not enough RAM to store cache metadata:

[   48.756416] 'OCF Core' volume operations registered
[   48.782582] 'Block Device' volume operations registered
[   48.784876] 'Atomic Writes NVMe' volume operations registered
[   48.790116] [Open-CAS] Not found configuration for upgrade. Standard module initialization.
[   48.794881] Open Cache Acceleration Software Linux Version 19.06.00.00000827 (3.10.0-693.el7.x86_64)::Module loaded successfully
[   51.415805] Inserting cache cache1
[   51.418145] Thread ocf_metadata_updater_cache1 started
[   51.418149] cache1: Metadata initialized
[   51.418323] cache1: Successfully added
[   51.420240] cache1: Cache mode : wt
[   51.422473] Thread cas_io_cache1_0 started
[   51.422688] Thread cas_io_cache1_1 started
[   51.422890] Thread cas_io_cache1_2 started
[   51.423122] Thread cas_io_cache1_3 started
[   51.423235] Thread cas_io_cache1_4 started
[   51.423386] Thread cas_io_cache1_5 started
[   51.423500] Thread cas_io_cache1_6 started
[   51.423508] Thread cas_io_cache1_7 started
[   51.423566] Thread cas_io_cache1_8 started
[   51.423719] Thread cas_io_cache1_9 started
[   51.423875] Thread cas_io_cache1_10 started
[   51.423971] Thread cas_io_cache1_11 started
[   51.424225] Thread cas_io_cache1_12 started
[   51.424353] Thread cas_io_cache1_13 started
[   51.424501] Thread cas_io_cache1_14 started
[   51.424612] Thread cas_io_cache1_15 started
[   51.424612] Thread cas_io_cache1_-1 started
[   51.424612] [Open-CAS] [Classifier] Initialized IO classifier
[   51.427412] cache1: Not enough free RAM for cache metadata to start cache
[   51.430615] cache1: Available RAM: 32356962304 B
[   51.432839] cache1: Needed RAM: 63837936025 B
[   51.434943] cache1: Attaching cache device failed
[   51.437311] BUG: unable to handle kernel paging request at ffffc90003ad9000
[   51.438272] IP: [<ffffffffc05be5bb>] ocf_volume_init+0x2b/0x110 [cas_cache]
[   51.438272] PGD 17fc62067 PUD 17fc63067 PMD 174697067 PTE 0
[   51.438272] Oops: 0002 [#1] SMP
[   51.438272] Modules linked in: cas_cache(OE) null_blk ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security iptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter xfs libcrc32c cas_disk(OE) sg ppdev joydev pcspkr parport_pc parport i2c_piix4 ip_tables btrfs xor raid6_pq sd_mod crc_t10dif crct10dif_generic sr_mod cdrom crct10dif_common ata_generic virtio_blk pata_acpi cirrus drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ttm drm ata_piix libata e1000 virtio_pci floppy
[   51.438272]  virtio_ring i2c_core serio_raw virtio [last unloaded: cas_cache]
[   51.438272] CPU: 7 PID: 6027 Comm: casadm Tainted: G           OE  ------------   3.10.0-693.el7.x86_64 #1
[   51.438272] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.7.5-0-ge51488c-20140602_164612-nilsson.home.kraxel.org 04/01/2014
[   51.438272] task: ffff8807e92e3f40 ti: ffff8800bb614000 task.ti: ffff8800bb614000
[   51.438272] RIP: 0010:[<ffffffffc05be5bb>]  [<ffffffffc05be5bb>] ocf_volume_init+0x2b/0x110 [cas_cache]
[   51.438272] RSP: 0018:ffff8800bb617c70  EFLAGS: 00010286
[   51.438272] RAX: ffffffffc05c3200 RBX: ffffc90003ad9000 RCX: 0000000000000000
[   51.438272] RDX: ffff8800bb617d70 RSI: ffff8807f3b5ba00 RDI: 0000000000000040
[   51.438272] RBP: ffff8800bb617c90 R08: ffff8800bb617c90 R09: 0000000000000000
[   51.438272] R10: 0000000000000000 R11: 0000000000000000 R12: ffffc90003cfa000
[   51.438272] R13: ffffc90003ad9000 R14: 00007fff7c09f710 R15: ffffc90003a99020
[   51.438272] FS:  00007f39dd745740(0000) GS:ffff88081f3c0000(0000) knlGS:0000000000000000
[   51.438272] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
[   51.438272] CR2: ffffc90003ad9000 CR3: 0000000035ec4000 CR4: 00000000000006e0
[   51.438272] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   51.438272] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   51.438272] Stack:
[   51.438272]  ffff8800bb617d70 ffffc90003cfa000 ffffc90003ad9000 00007fff7c09f710
[   51.438272]  ffff8800bb617cc8 ffffffffc05afd5f ffffc90003a98000 ffff8808147c8600
[   51.438272]  ffff8800bb617d70 00007fff7c09f710 0000000000000001 ffff8800bb617d48
[   51.438272] Call Trace:
[   51.438272]  [<ffffffffc05afd5f>] ocf_mngt_get_ram_needed+0x5f/0x100 [cas_cache]
[   51.438272]  [<ffffffffc05c108c>] cache_mngt_init_instance+0x22c/0x430 [cas_cache]
[   51.438272]  [<ffffffffc0597c80>] cas_service_ioctl_ctrl+0x16d0/0x1ad0 [cas_cache]
[   51.438272]  [<ffffffff8105a353>] ? x2apic_send_IPI_mask+0x13/0x20
[   51.438272]  [<ffffffff81050b5c>] ? native_smp_send_reschedule+0x4c/0x70
[   51.438272]  [<ffffffff810c0548>] ? resched_curr+0xa8/0xc0
[   51.438272]  [<ffffffff812151cd>] do_vfs_ioctl+0x33d/0x540
[   51.438272]  [<ffffffff812b75df>] ? file_has_perm+0x9f/0xb0
[   51.438272]  [<ffffffff81215471>] SyS_ioctl+0xa1/0xc0
[   51.438272]  [<ffffffff81086d66>] ? SyS_clone+0x16/0x20
[   51.438272]  [<ffffffff816b4fc9>] system_call_fastpath+0x16/0x1b
[   51.438272] Code: 0f 1f 44 00 00 55 48 85 f6 48 89 e5 41 56 41 55 41 54 53 48 8b 06 48 89 fb 8b 78 0c 0f 84 96 00 00 00 48 85 db 0f 84 8d 00 00 00 <48> 89 33 c6 43 18 00 be d0 80 00 00 49 89 d4 41 89 cd e8 5e 1e
[   51.438272] RIP  [<ffffffffc05be5bb>] ocf_volume_init+0x2b/0x110 [cas_cache]
[   51.438272]  RSP <ffff8800bb617c70>
[   51.438272] CR2: ffffc90003ad9000

### PR DESCRIPTION
**Pull request by robertbaldyga**
Fixes #86
Fixes #87

Signed-off-by: Robert Baldyga <robert.baldyga@intel.com>

### CODE REVIEW

**Comment by robertbaldyga** [comment]
@CAS-Linux-Jenkins retest this please

**Comment by Deixx** [comment]
retest this please

**Comment by KamilLepek** [comment]
@CAS-Linux-Jenkins retest this please

**Comment by mmichal10** [comment]
ocf is updated in #122

**Pull request closed without merging**
