### PR TITLE
test: Add file permissions test

### PR DESCRIPTION
**Pull request by rafalste**
Test files and directories permissions of git repo, build artifacts and installed items.

Needs https://github.com/intel-innersource/frameworks.validation.opencas.test-framework/pull/47

### CODE REVIEW

**Review by mmichal10 — DISMISSED** [review]

**Comment by rafalste** [comment]
retest this please

**Comment by rafalste** [comment]
retest this please

**Comment by rafalste** [comment]
retest this please

**Comment by karolinavelkaja** [comment]
@rafalste the conflicts here should be resolved or are expected?:)

**Comment by rafalste** [comment]
> @rafalste the conflicts here should be resolved or are expected?:)

@karolinavelkaja, fixed

**Review by mmichal10 — APPROVED** [review]

**Review by karolinavelkaja — APPROVED** [review]

**Pull request merged**
